[package]
name = "ggez_imgui_test"
version = "0.1.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.2"

gfx_core = "0.9.0"
gfx_device_gl = "0.16.0"

imgui = "0.0.23"
imgui-gfx-renderer = "0.0.23"